# Generated by Django 5.0.3 on 2024-03-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Tickets')),
                ('type_of_ticket', models.CharField(max_length=50)),
                ('start_validity', models.DateField(blank=True, null=True)),
                ('end_validity', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
