# Generated by Django 5.0.3 on 2024-04-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ticket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='key_after_success_payment',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
