# Generated by Django 5.0.3 on 2024-04-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_combined_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
    ]
