# Generated by Django 5.0.3 on 2024-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_qr_code_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
