# Generated by Django 5.0.3 on 2024-04-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code_url',
        ),
    ]
