# Generated by Django 5.0.3 on 2024-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_2',
            field=models.CharField(blank=True, help_text='Bâtiment, étage...', max_length=240, null=True),
        ),
    ]
