# Generated by Django 5.0.3 on 2024-04-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_shippingaddress_address_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
